"""
Django settings for block_api project.

Generated by 'django-admin startproject' using Django 5.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '')
MAX_HISTORY = 50

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DJANGO_DEBUG", default=0))
# DEBUG = False
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS").split(",")
FRONTEND_HOST = os.environ.get("FRONTEND_HOST", "http://localhost:8080/")
INTERNAL_IPS = [
    '127.0.0.1',
]

CORS_ALLOW_ALL_ORIGINS = True  # Для разработки, для продакшена CORS_ALLOWED_ORIGINS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-operation-uuid',
    'x-copy-block-id',
]
CORS_EXPOSE_HEADERS = ['X-Operation-UUID', 'x-copy-block-id']
CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS").split(",")

# Application definition

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(weeks=56),
    'REFRESH_TOKEN_LIFETIME': timedelta(weeks=60),
    "ALGORITHM": "HS256",
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'debug_toolbar',
    'corsheaders',
    'simple_history',
    'psqlextra',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
    'JSON_ENCODER': 'api.models.CustomJSONEncoder',
}

DEFAULT_JSON_ENCODER = 'api.models.CustomJSONEncoder'

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.EchoUUIDMiddleware',
]

ROOT_URLCONF = 'block_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'block_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# pg_dump -U [username] -h [host] -p [port] -d [database_name] -f [output_file]

DATABASES = {
    'default': {
        'ENGINE': 'psqlextra.backend',
        'NAME': os.getenv('SQL_NAME'),
        'USER': os.getenv('SQL_USER', ''),
        'PASSWORD': os.getenv('SQL_PASSWD', ''),
        'HOST': os.getenv('SQL_HOST', ''),
        'PORT': os.getenv('SQL_PORT', ''),
        'CONN_MAX_AGE': 600,
    },
    # 'target': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': os.getenv('SQL_NAME'),
    #     'USER': os.getenv('SQL_USER', ''),
    #     'PASSWORD': os.getenv('SQL_PASSWD', ''),
    #     'HOST': os.getenv('SQL_HOST', ''),
    #     'PORT': 5432,
    #     'CONN_MAX_AGE': 600,
    # },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
MAX_UPLOAD_SIZE = 5 * 1024 * 1024  # 5 MB
MAX_IMAGE_DIMENSIONS = (4096, 4096)  # Максимальные размеры изображения (ширина, высота)
ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/gif', 'image/webp']
THUMBNAIL_SIZE = (300, 300)  # Размер превью
JPEG_QUALITY = 85  # Качество сжатия JPEG
OPTIMIZE_UPLOADS = True  # Оптимизировать изображения при загрузке

# Storage backend (переключение между локальным и облачным)
# Для облачного хранилища установить: pip install django-storages boto3
# и настроить AWS_* или другие переменные окружения
FILE_STORAGE_BACKEND = os.environ.get('FILE_STORAGE_BACKEND', 'local')  # 'local' или 's3'

# S3 настройки (для cloud.ru Object Storage или AWS S3)
if FILE_STORAGE_BACKEND == 's3':
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')  # Для cloud.ru
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ru-central1')
    AWS_QUERYSTRING_AUTH = False  # Публичные URL

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
    },
    'formatters': {
        'detailed': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        '__main__': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

LIMIT_BLOCKS = 1000
# максимальная глубина загрузки блоков за один раз.
# последний уровень отрезается сериалайзером что бы гарантировать что у блоков на последнем урвоне будут children
MAX_DEPTH_LOAD = 5
# максимальная глубины для загрузки блоков по ссылке. (
# для такой загрузки отключена проверка прав) последний уровень отрежется.
LINK_LOAD_DEPTH_LIMIT = 10

# UUID служебного блока, который используется как источник для "битых" ссылок
SERVICE_BLOCK_ID = os.environ.get('SERVICE_BLOCK_ID')



RABBITMQ_USER = os.environ.get('RABBITMQ_USER')
RABBITMQ_PASS = os.environ.get('RABBITMQ_PASS')
RABBITMQ_HOST_PORT = os.environ.get('RABBITMQ_HOST_PORT')
RABBITMQ_EXCHANGES = os.environ.get('RABBITMQ_EXCHANGES')
RABBITMQ_QUEUE = os.environ.get('RABBITMQ_QUEUE')
RABBITMQ_ROUTING_KEY = os.environ.get('RABBITMQ_ROUTING_KEY')
REDIS_HOST = os.environ.get('REDIS_HOST')


CELERY_BROKER_URL = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@{RABBITMQ_HOST_PORT}//'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:6379/0'
CELERY_RESULT_EXPIRES = 3600
CELERY_TASK_SOFT_TIME_LIMIT = 300
CELERY_TASK_TIME_LIMIT = 360
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# ============================================================================
# Настройки напоминаний и уведомлений
# ============================================================================

# Лимиты на пользователя
MAX_REMINDERS_PER_USER = 100
MAX_SUBSCRIPTIONS_PER_USER = 50

# Rate limiting
MIN_NOTIFICATION_INTERVAL_SECONDS = 60  # Не чаще 1 раз в минуту на подписку

# Telegram link token
TELEGRAM_LINK_TOKEN_EXPIRY_MINUTES = 15

# Агрегация уведомлений
NOTIFICATION_AGGREGATION_WINDOW_SECONDS = 60  # Собираем изменения за 1 минуту

# Telegram
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_SECRET = os.environ.get('TELEGRAM_BOT_SECRET', '')
TELEGRAM_BOT_USERNAME = os.environ.get('TELEGRAM_BOT_USERNAME', '')

# Email
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'OmniMap <noreply@omnimap.ru>')

# Push (VAPID keys)
VAPID_PUBLIC_KEY = os.environ.get('VAPID_PUBLIC_KEY', '')
VAPID_PRIVATE_KEY = os.environ.get('VAPID_PRIVATE_KEY', '')
VAPID_ADMIN_EMAIL = os.environ.get('VAPID_ADMIN_EMAIL', '')

# Celery Beat Schedule (периодические задачи)
CELERY_BEAT_SCHEDULE = {
    'check-reminders-every-minute': {
        'task': 'api.tasks.check_pending_reminders',
        'schedule': 60.0,  # каждую минуту
    },
    'process-pending-notifications': {
        'task': 'api.tasks.process_pending_notifications',
        'schedule': 60.0,  # каждую минуту
    },
    'cleanup-expired-telegram-tokens': {
        'task': 'api.tasks.cleanup_expired_telegram_tokens',
        'schedule': 6 * 60 * 60,  # каждые 6 часов
    },
}
