# Generated by Django 5.0.5 on 2024-10-07 11:25

import django.db.models.deletion
import simple_history.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('inherited', 'Inherited'), ('public_ed', 'Public Editable')], default='inherited', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parent_blocks', to='api.block')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
                ('editable_by_users', models.ManyToManyField(blank=True, related_name='editable_blocks', to=settings.AUTH_USER_MODEL)),
                ('visible_to_users', models.ManyToManyField(blank=True, related_name='visible_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('content_change', models.JSONField(blank=True, default=dict, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='api.block')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('editable_blocks', models.ManyToManyField(related_name='group_editable_blocks', to='api.block')),
                ('members', models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL)),
                ('visible_blocks', models.ManyToManyField(related_name='group_visible_blocks', to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBlock',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid6, editable=False)),
                ('access_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('inherited', 'Inherited'), ('public_ed', 'Public Editable')], default='inherited', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical block',
                'verbose_name_plural': 'historical blocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
