# Generated by Django 4.2.23 on 2025-12-27 13:23

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        upload_to=api.models.block_file_upload_path,
                        verbose_name="Файл изображения",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.block_thumbnail_upload_path,
                        verbose_name="Превью",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="MIME-тип"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="Размер в байтах")),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Высота"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="api.block",
                        verbose_name="Блок",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл блока",
                "verbose_name_plural": "Файлы блоков",
                "ordering": ["-created_at"],
            },
        ),
    ]
