# Generated by Django 5.0.5 on 2024-10-07 12:04

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='editable_blocks',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='visible_blocks',
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.CharField(default=uuid6.uuid6, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='id',
            field=models.CharField(db_index=True, default=uuid6.uuid6, editable=False, max_length=36),
        ),
        migrations.DeleteModel(
            name='BlockChangeLog',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
