# Generated by Django 4.2.23 on 2025-12-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_add_blockfile_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockChangeSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("depth", models.SmallIntegerField(default=1)),
                ("on_text_change", models.BooleanField(default=True)),
                ("on_data_change", models.BooleanField(default=True)),
                ("on_move", models.BooleanField(default=True)),
                ("on_child_add", models.BooleanField(default=True)),
                ("on_child_delete", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_notification_at", models.DateTimeField(blank=True, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="api.block",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на изменения",
                "verbose_name_plural": "Подписки на изменения",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telegram_enabled", models.BooleanField(default=False)),
                ("telegram_linked_at", models.DateTimeField(blank=True, null=True)),
                ("email_enabled", models.BooleanField(default=True)),
                (
                    "email_mode",
                    models.CharField(
                        choices=[
                            ("off", "Выключено"),
                            ("fallback", "Если Telegram недоступен"),
                            ("always", "Всегда дублировать"),
                        ],
                        default="fallback",
                        max_length=20,
                    ),
                ),
                ("push_enabled", models.BooleanField(default=False)),
                ("push_subscription", models.JSONField(blank=True, null=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
        migrations.CreateModel(
            name="TelegramLinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен привязки Telegram",
                "verbose_name_plural": "Токены привязки Telegram",
                "indexes": [
                    models.Index(
                        fields=["token", "used"], name="api_telegra_token_e7857e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PendingNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("text_change", "Изменён текст"),
                            ("data_change", "Изменены свойства"),
                            ("move", "Блок перемещён"),
                            ("child_add", "Добавлен дочерний блок"),
                            ("child_delete", "Удалён дочерний блок"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_notifications",
                        to="api.block",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_notifications",
                        to="api.blockchangesubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отложенное уведомление",
                "verbose_name_plural": "Отложенные уведомления",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="api_pending_user_id_949a9f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remind_at", models.DateTimeField(db_index=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("message", models.TextField(blank=True)),
                (
                    "repeat",
                    models.CharField(
                        choices=[
                            ("none", "Однократно"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder",
                        to="api.block",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Напоминание",
                "verbose_name_plural": "Напоминания",
                "indexes": [
                    models.Index(
                        fields=["remind_at", "is_sent"],
                        name="api_blockre_remind__0eac36_idx",
                    ),
                    models.Index(
                        fields=["user", "is_sent"],
                        name="api_blockre_user_id_37e1cc_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="blockchangesubscription",
            index=models.Index(fields=["user"], name="api_blockch_user_id_55bc65_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="blockchangesubscription",
            unique_together={("block", "user")},
        ),
    ]
